#server:
#  servlet:
#    context-path: /zdjky

spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://192.168.1.116:3306/zdjky?characterEncoding=utf-8&useSSL=false
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
  jpa:
    show-sql: true

jdbc.driver: com.mysql.jdbc.Driver
jdbc.url: jdbc:mysql://192.168.1.140:3306/zdjky?characterEncoding=utf-8&useSSL=false
jdbc.username: root
jdbc.password: 123456
jdbc.filters: stat
jdbc.maxActive: 20
jdbc.initialSize: 1
jdbc.maxWait: 60000
jdbc.minIdle: 1
jdbc.timeBetweenEvictionRunsMillis: 60000
jdbc.minEvictableIdleTimeMillis: 300000
jdbc.validationQuery: select 'x'
jdbc.testWhileIdle: true
jdbc.testOnBorrow: false
jdbc.testOnReturn: false
jdbc.poolPreparedStatements: true
jdbc.maxOpenPreparedStatements: 20


mybatis:
  typeAliasesPackage: com.foxconn.model
  mapperLocations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml

#mybatis_config_file: mybatis-config.xml
#mapper_path: /mapper/*Mapper.xml
#type_aliases_package: com.foxconn.model


#logging:
#  config: classpath:logback-spring.xml


